# The version of the config. If your config is outdated you'll get a warning.
# Breaking changes may happen, please refer to the changelog for more information.
version: 0

# Possible values: { critical, error, warning, info, verbose, debug }
logging_level: info

# Decide which browser engine to use. Currently only Firefox is supported.
browser_engine: firefox

# This part is for the discord integration.
bot_token: <insert bot token here>

# The address of the watched coin.
coin_address: <insert coin address here>