# The version of the config. If your config is outdated you'll get a warning.
# Breaking changes may happen, please refer to the changelog for more information.
version: 0

# Possible values: { critical, error, warning, info, verbose, debug }
logging_level: info

# Decide which browser engine to use. Currently only Firefox is supported.
browser_engine: firefox

# These infos are required for web requests.
token:
  # Supported: avalanche, eth, fantom, polygon, bsc
  chain: <insert chain here>
  # The address of the token
  address: <insert token address here>

# This is part of the discord integration.
discord:
  bot_token: <insert discord bot token here>

# This is part of the dex.guru integration. 
dex_guru_api_key: <insert dex.guru api key here>

# The delay to wait for the pages to load (in seconds).
page_delay: 5